### ISSUE TITLE
Compiling under VS2022

### ISSUE THREAD

**Issue by maksw2** [Sectonidse/SourceDEFUN#7]
errors taken from actions:

 "D:\a\SourceDEFUN\SourceDEFUN\SourceDEFUN.sln" (default target) (1) ->
       "D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj.metaproj" (default target) (2) ->
       "D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj" (default target) (6) ->
       (Link target) -> 
         libucrt.lib(hypot.obj) : error LNK2005: _hypot already defined in shaderlib.lib(BaseShader.obj) [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         pbr_dx9.obj : error LNK2001: unresolved external symbol "class ConVar mat_allow_parallax_cubemaps" (?mat_allow_parallax_cubemaps@@3VConVar@@A) [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(convar.obj) : error LNK2019: unresolved external symbol _sscanf referenced in function "private: bool __thiscall ConVar::InternalSetColorFromString(char const *)" (?InternalSetColorFromString@ConVar@@AAE_NPBD@Z) [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(convar.obj) : error LNK2019: unresolved external symbol __vsnprintf referenced in function "void __cdecl AppendPrintf(char *,unsigned int,char const *,...)" (?AppendPrintf@@YAXPADIPBDZZ) [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(strtools.obj) : error LNK2001: unresolved external symbol __vsnprintf [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(utlstring.obj) : error LNK2001: unresolved external symbol __vsnprintf [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(strtools.obj) : error LNK2019: unresolved external symbol __vsnwprintf referenced in function "int __cdecl V_snwprintf(wchar_t *,int,wchar_t const *,...)" (?V_snwprintf@@YAHPA_WHPB_WZZ) [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(interface.obj) : error LNK2019: unresolved external symbol _sprintf referenced in function "void __cdecl DebugKernelMemoryObjectName(char *)" (?DebugKernelMemoryObjectName@@YAXPAD@Z) [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         Release_dx9\game_shader_generic_deferred.dll : fatal error LNK1120: 5 unresolved externals [D:\a\SourceDEFUN\SourceDEFUN\materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]

    910 Warning(s)
    39 Error(s)

Time Elapsed 00:01:27.21
Error: Process completed with exit code 1.

**Comment by Sectonidse** [comment]
Fixed one of the errors, i don't really know how to fix the rest of them
Current log:
```
"SourceDEFUN.sln" (default target) (1) ->
       "materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj.metaproj" (default target) (2) ->
       "materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj" (default target) (6) ->
       (Link target) -> 
         libucrt.lib(hypot.obj) : error LNK2005: _hypot already defined in shaderlib.lib(BaseShader.obj) [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(convar.obj) : error LNK2019: unresolved external symbol _sscanf referenced in function "private: bool __thiscall ConVar::InternalSetColorFromString(char const *)" (?InternalSetColorFromString@ConVar@@AAE_NPBD@Z) [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(convar.obj) : error LNK2019: unresolved external symbol __vsnprintf referenced in function "void __cdecl AppendPrintf(char *,unsigned int,char const *,...)" (?AppendPrintf@@YAXPADIPBDZZ) [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(strtools.obj) : error LNK2001: unresolved external symbol __vsnprintf [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(utlstring.obj) : error LNK2001: unresolved external symbol __vsnprintf [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(strtools.obj) : error LNK2019: unresolved external symbol __vsnwprintf referenced in function "int __cdecl V_snwprintf(wchar_t *,int,wchar_t const *,...)" (?V_snwprintf@@YAHPA_WHPB_WZZ) [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         tier1.lib(interface.obj) : error LNK2019: unresolved external symbol _sprintf referenced in function "void __cdecl DebugKernelMemoryObjectName(char *)" (?DebugKernelMemoryObjectName@@YAXPAD@Z) [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
         Release_dx9\game_shader_generic_deferred.dll : fatal error LNK1120: 4 unresolved externals [materialsystem\swarmshaders\game_shader_generic_swarm.vcxproj]
```
910 Warnings (holy shit)
38 Errors

------------

https://github.com/Sectonidse/SourceDEFUN/blob/3b02a1d804e0fa1ca69d0eef0919438ad6dfa4e1/public/tier1/strtools.h#L225-L227

This must be the origins of vsnprintf,

https://github.com/Sectonidse/SourceDEFUN/blob/3b02a1d804e0fa1ca69d0eef0919438ad6dfa4e1/public/tier1/strtools.h#L185

And vsnwprintf,

https://github.com/Sectonidse/SourceDEFUN/blob/f28fc7a96433aff74af3d2f65dd4ee1c74a8e3cb/public/tier0/wchartypes.h#L69

And lastly sprintf?

Couldn't find sscanf though.

**Comment by Sectonidse** [comment]
I think this might be the reason why: https://github.com/Sectonidse/SourceDEFUN/commit/f82f8b0f934f9334392f3ba21b35fa971c51cbcf

I grabbed this .lib from Alien Swam: Reactive Drop out of frustration and it haven't changed ever since this commit

**Comment by maksw2** [comment]
tier1.lib is fully closed source and i'm pretty certain it's the same for everything.

**Comment by maksw2** [comment]
i fixed a lot of these errors, look at pr #8

**Comment by Sectonidse** [comment]
Okay so i experimented and you were right, the MD5 hashes must be taking dates into account then.
I'm gonna take a look at the pr now.

**Comment by maksw2** [comment]
change bug to help wanted

**Comment by Sectonidse** [comment]
I think we'll use CMake instead of MSBuild now.
