### ISSUE TITLE
Generate a solution with CMake or use WAF

### ISSUE THREAD

**Issue by maksw2** [Sectonidse/SourceDEFUN#9]

**Comment by Sectonidse** [comment]
cmake what? You mean compile using cmake instead of msbuild?

**Comment by maksw2** [comment]
nah, i mean to generate a solution with.

**Comment by Sectonidse** [comment]
> you can add me and assign this to me.

assigned

**Comment by maksw2** [comment]
after a bit of thinking i settled on cmake.

**Comment by maksw2** [comment]
it's about 75% done, will be done today.
